### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [three11/optisize#33]
Hi...
Came across your amazing project, I'm a logo/icon design who loves to help contribute to amazing open source projects using my design skills. I want to help create a Logo/Icon for your project as my free contribution to your project.

Working on a logo concept already, I will update it here once it is finished, so you can give me your feedback on the changes you might want.

Your response will be greatly appreciated...
Regards!

**Comment by scriptex** [comment]
Woah! A really great idea!!! I am looking forward to see your ideas :) Can't wait

**Comment by chimzycash** [comment]
I really appreciate your quick response... Would get the idea concept ready for your feedback.

**Comment by chimzycash** [comment]
Hello...
Here is my idea concept I came up with... I would love to read your feedback., You can also suggest the preferred logo color of your choice.

![LOGO DESIGN_OPTISIZE_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/57990930-3ccf7e80-7aa3-11e9-89b5-6ce2bdafdea1.jpg)
![LOGO DESIGN_OPTISIZE_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/57990941-4527b980-7aa3-11e9-8e42-4246d68ea195.jpg)
![LOGO DESIGN_OPTISIZE_BACKGROUND_3](https://user-images.githubusercontent.com/37814297/57990990-a94a7d80-7aa3-11e9-8681-f6f8ff2d0268.jpg)
![LOGO DESIGN_OPTISIZE_BACKGROUND_4](https://user-images.githubusercontent.com/37814297/57990932-3d681500-7aa3-11e9-8563-173543808da3.jpg)
![LOGO DESIGN_OPTISIZE_BACKGROUND_5](https://user-images.githubusercontent.com/37814297/57990933-3e00ab80-7aa3-11e9-887a-371208ab0047.jpg)
![LOGO DESIGN_OPTISIZE_idea concept_NEW](https://user-images.githubusercontent.com/37814297/57990935-3f31d880-7aa3-11e9-9675-bbb42f986585.jpg)

**Comment by scriptex** [comment]
It looks awesome! We (everyone in the organization) really liked the concept and the actual implementation. Right now I am not sure about the color as green looks good here but maybe you can provide a vector file in which we can edit the color as needed?

**Comment by chimzycash** [comment]
Here are a few color options that work well...

![LOGO DESIGN_OPTISIZE_BACKGROUND_1_color test 1](https://user-images.githubusercontent.com/37814297/58025866-455c9f00-7b0d-11e9-9e52-e6e6f951a1cf.jpg)
![LOGO DESIGN_OPTISIZE_BACKGROUND_1_color test 2](https://user-images.githubusercontent.com/37814297/58025868-455c9f00-7b0d-11e9-81fe-0b915b52a54a.jpg)

**Comment by scriptex** [comment]
Yes! I like the purple and orange colors.
We can wrap this up and finalize it if you are satisfied. 
If yes, then please open a PR :)

**Comment by chimzycash** [comment]
Glad you liked the design and color options. The Purple color works really well.
Created the final design with the purple color... Will prepare all the PNG files including the vector files for your use.

![LOGO DESIGN_OPTISIZE_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/58134136-c1460c80-7c1d-11e9-8403-4b936c5514ea.jpg)
![LOGO DESIGN_OPTISIZE_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/58134142-c2773980-7c1d-11e9-9697-e7ad29d2f84f.jpg)
![LOGO DESIGN_OPTISIZE_BACKGROUND_3](https://user-images.githubusercontent.com/37814297/58134137-c1dea300-7c1d-11e9-82aa-0b42fb238770.jpg)
![LOGO DESIGN_OPTISIZE_BACKGROUND_4](https://user-images.githubusercontent.com/37814297/58134139-c2773980-7c1d-11e9-8c4b-9dca6e12a774.jpg)

**Comment by scriptex** [comment]
🎉 🎉 🎉 
The logo has been added in a612670fd4815092aa2f5c7cef69efa5309dcff6
@chimzycash Thank you very much for your contribution! 👏 👏 👏

**Comment by chimzycash** [comment]
Here is the Google Drive link containing all the PNG files and Vector files for your use.
https://drive.google.com/drive/folders/1zTnr1G0vx7XZ-8ZmRX0-vIkWPulSHNAu?usp=sharing

You can notify me if you need a logo design on any open source projects... I will be glad to contribute

**Comment by scriptex** [comment]
Thank you once again, I will get in touch if I need a new logo or any other design work. Keep up the good work! Was a pleasure collaborating with you :)
